### ISSUE TITLE
Multiples issues after updating from 1.0.3 to 2.0.1

### ISSUE THREAD

**Issue by Johan22** [webdriverio/gulp-webdriver#46]
When I update gulp-webdriver to the latest version, I have problems with my differents tests.
The ones starting by creating a newbrowser like this : 

var newbrowser = webdriverio.remote(browser.options).init();
        return newbrowser
            .url(browser.options.baseUrl + variables.url.home)
...
Error 1 : the test is passed instantly (but it isn't in reality)

I have an other test beggining like this who fails after a few clicks : 
it('Search Manhattan with some criteria', function() {
        return browser
            .url(browser.options.baseUrl + variables.url.home)
            ...
Error 2 : browser.url(...).click(...).click(...).click(...).waitForVisible(...).click is not a function

For an other test I have this issue : 
Error 3 : done is not a function

I can give you more details on my different test or my configuration files and nodesmodules versions if you need.

**Comment by christian-bromann** [comment]
> var newbrowser = webdriverio.remote(browser.options).init();
> return newbrowser
> .url(browser.options.baseUrl + variables.url.home)

Why do you create your own instance? This is done by the wdio test runner

> Error 2 : browser.url(...).click(...).click(...).click(...).waitForVisible(...).click is not a function

Are you executing your tests in sync or async mode?

> Error 3 : done is not a function

Seems you executing it in sync mode. In this case we don't provide a done function because there is no need for it if all commands getting executed in sync mode

**Comment by Johan22** [comment]
Why do you create your own instance? This is done by the wdio test runner
=> We thought it was mandatory to create a new instance for each test requiring a session id (such as login test). But I tried to use directly the browser instance for the login test and it seems to work properly so I can change that...

Are you executing your tests in sync or async mode?
=> I think I understand why all my tests fails. With the 1.0.3 version of gulp-webdriver, my tests were asynchronous. I could chained multiples click for examples. But when I upgrade to the gulp-webdriver 2.0.1, all my tests become synchronous and I need to change the syntax to make them work (I have to do browser.click(); browser.click(); instead of browser.click().click()...).

So now my question is how can I switch from async to sync and vice versa ? Which is the best mode in your opinion?

Thanks

**Comment by christian-bromann** [comment]
> So now my question is how can I switch from async to sync and vice versa ?

There is a flag in your config file called sync, please see http://webdriver.io/guide/testrunner/configurationfile.html

> Which is the best mode in your opinion?

Use synchronous mode, it helps to write good tests

Ok I don't think anything is wrong with the package. Closing
